#PGADMIN ID
#Tue May 19 12:04:13 EEST 2026
db.jdbcUrl=jdbc\:postgresql\://YOUR_HOST\:5432/YOUR_DB
db.password=YOUR_DB_PASSWORD
db.user=YOUR_DB_USER
kafkaUiPassword=admin
kafkaUiToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImEwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMSIsInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE3NzkxODE0MTEsImV4cCI6MTc3OTIxMDIxMX0.EKZlBSbGbhN5ERqqDeVrkPfD-N-YORm2C3w-M45aYOE
kafkaUiUsername=admin
message_id=121bf18b-8024-4d2a-b10f-e3fae99fb70a
